### ISSUE TITLE
Functionality problems

### ISSUE THREAD

**Issue by jhong84** [VIP-eDemocracy/VIP-Integration-Testing#1]
1. No response while choosing a mission after admin log in
2. Can only do things in admin mode
3. “Change language” no response
4. Nothing show up while clicking “add questions” to a form
5. No response while clicking “create new option set” for a question
6. Some type of questions cannot be created
7. Cannot delete the element that has been created
8. Cannot add new users because “Assignment” cannot be chosen
9. No response while clicking “Add selected questions to form” under “Add questions to form”
10. Error page appeared while trying to create option set

![errorpage](https://cloud.githubusercontent.com/assets/5727930/7034718/47acfda4-dd50-11e4-9f94-0c43c7094f9d.png)

**Comment by treywashington** [comment]
Should be working now.
